- common/influxdb/influxdb.go
- docs/en/elasticsearch-sink.md
- docs/en/honeycomb-sink.md
- docs/en/influxdb-sink.md
- docs/en/kafka-sink.md
- docs/en/log-sink.md
- docs/en/riemann-sink.md
add english documentes for sinks
> add english documentes for sinks

- Makefile
- README.md
- deploy/deploy.yaml
- eventer.go
- version/version.go
> add new docker images and update docs

- docs/en/elasticsearch-sink.md
> add notice

- docs/en/mysql-sink.md
When use mysql-sink to push events.
databases kube-events and tables kube-events don't exist so we need to first build table
> Add mysql-sink sql

- README.md
- deploy/deploy.yaml
> change image version in doc

- README.md
- deploy/deploy.yaml
> change apiversion to apps/v1

- sinks/influxdb/influxdb.go
which would lead to failure of creating a database or a retention policy
> fix(influxdb.go): fix database name uses in queries without ""

- README.md
**PR类型是什么？**
>
> /kind bug
> /kind design
documentation
documentation add webhook sink 
Fixes #
```docs
```
**测试/最终运行结果**:
> docs: ✏️ add webhook 

- sinks/sls/sls.go
**PR类型是什么？**
> 
> /kind bug
> /kind design
bug
修复了一个sls的客户端无法识别project问题
Fixes #
None
```docs
```
**测试/最终运行结果**:
> fix sls client

- common/filters/generic_filter.go
- common/filters/generic_filter_test.go
**PR类型是什么？**
>
> bug
1.when enable regexp and empty regexp， all events should be matched
空正则不应该过滤事件
2.when event field not exist,  generic filter should be return false
事件字段不存在的时候，直接过滤掉，不应该进行剩下的逻辑判断。
例子：
```
const (
webhookSinkValid = "https://oapi.dingtalk.com/robot/send?access_token=token&level=Normal&namespaces=a,b&kinds=c,d&header=contentType=demo&header=content2=3"
)
```
https://github.com/AliyunContainerService/kube-eventer/blob/548ea0a3a748499e424da1af514f1fe49ddc1fa6/sinks/webhook/webhook.go#L159
当webhook sink uri中没有定义`reason`的时候，`ReasonsFilter` …
> fix: 🐛 when enable regexp, empty regexp should be matched

- common/mysql/mysql.go
**PR类型是什么？**
>
> feature
support mysql sink config mysql dbname.
支持从mysql sink url中读取数据库名。
https://github.com/AliyunContainerService/kube-eventer/issues/96
Fixes #
None
```docs
```
**测试/最终运行结果**:
> feat: 🎸 support mysql sink config mysql dbname

- common/filters/generic_filter.go
- common/filters/generic_filter_test.go
- sinks/webhook/webhook.go
- sinks/webhook/webhook_test.go
**PR类型是什么？**
> /kind bug
> /kind design
**bug**
fix the event filter failed.
Fixes #
None
```docs
```
**测试/最终运行结果**:
> fix filter event

- README.md
- deploy/deploy.yaml
**PR类型是什么？**
>
> /kind release 
release image 
Fixes #119 
None
> release kube-eventer image due to bugfix

- docs/en/webhook-sink.md
- sinks/webhook/webhook.go
**PR类型是什么？**
>
> /kind bug
> /kind design
documentation
update the webhook doc.
Fixes #119 
None
```docs
```
**测试/最终运行结果**:
> update webhook template

- sinks/webhook/webhook.go
**PR类型是什么？**
>
> /kind bug
> /kind design
bug
webhook event display be truncated.
Fixes #
None
```docs
```
**测试/最终运行结果**:
> fix event msg display

- sinks/elasticsearch/driver.go
**PR类型是什么？**
>
Part of k8s resources FirstOccurrenceTimestamp/LastOccurrenceTimestamp is nil
https://github.com/kubernetes/kubernetes/pull/89999
Fixes #
```docs
```
**测试/最终运行结果**:
> Fix event the timestamp is < unknown >

- sinks/webhook/webhook.go
**PR类型是什么？**
>
> /kind bug
Fixes #130 
NONE
> fix webhook json

- docs/en/webhook-sink.md
**PR类型是什么？**
>
> /kind bug
> /kind design
/kind documentation
no documentation about custom body configmap key, i just share my slack templates, tks
Fixes https://github.com/AliyunContainerService/kube-eventer/issues/138
```docs
```
**测试/最终运行结果**:
> add slack example

- sinks/webhook/webhook.go
**PR类型是什么？**
ref https://github.com/AliyunContainerService/kube-eventer/issues/137
>
> /kind bug
> /kind design
Fixes #
```docs
```
**测试/最终运行结果**:
> add response body in error message to help debug

- docs/en/mysql-sink.md
- manager/manager.go
- sinks/wechat/wechat.go
Signed-off-by: Liu Ming <hit_oak_tree@126.com>
**PR类型是什么？**
typos in document
Fixes #
```docs
```
**测试/最终运行结果**:
> docs: fix typo

- deploy/Dockerfile
- eventer.go
defined uid and gid for non-root user
health check handler function added
**PR类型是什么？**
>
> /kind bug
> /kind design
Fixes #
```docs
```
**测试/最终运行结果**:
> to use non-root user to run process inside container

- docs/en/webhook-sink.md
**PR类型是什么？**
> /kind <documentation>
> /kind bug
> /kind design
- **update the webhook doc**
Fixes #
```docs
NONE
```
**测试/最终运行结果**:
> update webhook doc

- deploy/Dockerfile
- sinks/sls/sls.go
**PR类型是什么？**
>
> /kind bug
> /kind design
Fixes #
```docs
```
**测试/最终运行结果**:
> bugfix when using sls sink with ak/sk

- docs/en/webhook-sink.md
**PR类型是什么？**
>
```
add webhook feishu example
```
Fixes #
```docs
NONE
```
**测试/最终运行结果**:
> add feishu example

- deploy/deploy.yaml
**PR类型是什么？**
>
release latest image version
Fixes #129
> release latest image version

- docs/en/webhook-sink.md
**PR类型是什么？**
>
```docs
add feishu v2 example
```
Fixes #
```docs
NONE
```
> add feishu v2 example

- sinks/webhook/webhook.go
**PR类型是什么？**
bug
>
> /kind bug
> /kind design
webHook body 反序列化失败
Fixes #170 
NONE
```docs
```
**测试/最终运行结果**:
> webhook body encoding

- docs/en/sls-sink.md
[documentation] How to config aliyun access key in sls sink doc.
**PR类型是什么？**
<kind>documentation</kind>
doc for how to config aliyun access key in sls sink.
Fixes #
https://github.com/AliyunContainerService/kube-eventer/issues/183
NONE
**测试/最终运行结果**:
NONE
> How to config aliyun access key in sls sink doc.

- README.md
**PR类型是什么？**
>
> /kind bug
> /kind design
Fixes #
```docs
```
**测试/最终运行结果**:
> ClusterRole add get configmap authority

- common/mysql/mysql.go
- docs/en/mysql-sink.md
**PR类型是什么？**
>
> /kind bug
> /kind design
**design** 
Fixes #153
NONE
```docs
```
**测试/最终运行结果**:
> mysql支持自定义表

- sinks/sls/sls.go
**PR类型是什么？**
>
> /kind bug
> /kind design
Fixes #
```docs
```
**测试/最终运行结果**:
> fix create sls cli from metadata

- sinks/webhook/webhook_test.go
**PR类型是什么？**
>
> /kind bug
> /kind design
> 
/kind documentation
add test cases
none
Fixes #
nothing
```docs
```
**测试/最终运行结果**:
> add test for render message

- deploy/deploy-for-sls(managed cluster).yaml
- deploy/deploy-for-sls(normal cluster).yaml
- docs/en/dingtalk-sink.md
- sinks/dingtalk/dingtalk.go
- sinks/dingtalk/dingtalk_test.go
**PR类型是什么？**
>
> /kind bug
> /kind design
Fixes #
```docs
```
**测试/最终运行结果**:
> update deploy yaml

- docs/en/webhook-sink.md
**PR类型是什么？**
/kind bug
Fixes #
```docs
```
**测试/最终运行结果**:
> modify feishu example configmap name

- eventer.go
- metrics/prometheus/judge.go
- metrics/prometheus/metrics.go
- sources/factory.go
- sources/kubernetes/kubernetes_source.go
Signed-off-by: Qiaozp <qiaozhongpei.qzp@alibaba-inc.com>
**PR类型是什么？**
>
> /kind bug
> /kind design
Feat in this comment: https://github.com/AliyunContainerService/kube-eventer/pull/251#issuecomment-1369455903
Fixes #
```docs
```
**测试/最终运行结果**:
> Feat: add event metrics switch

- metrics/prometheus/judge.go
- metrics/prometheus/metrics.go
Signed-off-by: Qiaozp <qiaozhongpei.qzp@alibaba-inc.com>
**PR类型是什么？**
>
> /kind bug
> /kind design
Refine some metrics and judegment.
None
None
**测试/最终运行结果**:
> refine event metrics

- docs/en/sls-sink.md
- sinks/sls/sls.go
- sinks/sls/sls_test.go
Support SLS sink with external labels.
e.g. URI: &label=RegionId,test_regionId&label=UserId,test_uid.
> support sls sink with external labels.

- docs/en/sls-sink.md
- sinks/sls/sls.go
- sinks/sls/sls_test.go
fix bugs when parse multi sls external labels
> fix bugs when parse multi sls external labels

- docs/en/elasticsearch-sink.md
refine elasticsearch readme for index define
> refine elasticsearch readme for index define

- common/kubernetes/configs.go
- common/mysql/mysql.go
- docs/en/mysql-sink.md
- sinks/mysql/mysql.go
- sinks/webhook/webhook.go
> fix mysql sink with wrong table name

- sinks/sls/sls.go
**PR类型是什么？**
> /kind bug
Failed to send log list with producer, PostBodyTooLarge
> fix: producer logs too large
